### PR TITLE
fixes #35 - Configure upload directory and reference a local persistent volume

### LINKED ISSUE #35: Configure upload directory and reference a local persistent volumne
When uploading a rather large uber jar, it fails to start due to not enough space on device. 
As there is no way of configuring the upload directory it would be good to have it configured to the underlying host system. (https://dcos.io/docs/1.9/storage/persistent-volume/)
Per default the jobmanager.web.upload.dir points to the jobmanager.web.tmpdir, which again references the system tmp folder.
See also https://ci.apache.org/projects/flink/flink-docs-release-1.2/setup/config.html

### PR DESCRIPTION
**Pull request by ANierbeck**

### CODE REVIEW

**Comment by EronWright** [comment]
@ANierbeck The marathon template doesn't configure the task manager container, only the job manager.   Unless I am mistaken, this fix would benefit only the job manager.

**Comment by ANierbeck** [comment]
ok ... 
do you have a pointer on where to find that?

**Comment by EronWright** [comment]
I mean, the issue cannot be fixed without some changes to Flink itself.   It is Flink that creates the Task Manager containers, and so would need to acquire volumes as Marathon does.   Sorry to dissuade you but the procedure is rather complicated.


I think we should close this PR now.


________________________________

**Comment by ANierbeck** [comment]
ok ... might be true, but the issue already is an issue for the job manager, that one also might run into the issue of no space left on device ... especially when uploading more then one gigantic uber-jar

**Comment by EronWright** [comment]
@ANierbeck I doubt the `taskmanager.tmp.dirs` option would help with general disk space issues.   Volumes increase the complexity so I'm inclined to close this, in favor of an improvement to Flink to allocate disks for the Task Manager.   

To briefly state what would be involved: Flink acts as a Mesos framework.  As a framework it must reserve disk resources and create volumes as part of offer handling.   Marathon makes this look easy but Marathon isn't involved here.    Flink uses Netflix Fenzo under the hood to process offers, and it may require an enhancement to be useful here (especially if multiple disks per TM are desired).  See [Netflix/Fenzo#83](https://github.com/Netflix/Fenzo/issues/83).

**Comment by joerg84** [comment]
@EronWright the uploadDir is on the jobmanager which is not started by Fenzo, or?

**Comment by EronWright** [comment]
It is true that the JM stores the uploaded JAR, then each TM downloads it to heir respective containers.

**Pull request closed without merging**
