### PR TITLE
fixes java issue

### PR DESCRIPTION
**Pull request by ANierbeck**
This could fix the wrong java version issue, especially the explicit setting of the java version

### CODE REVIEW

**Comment by joerg84** [comment]
@ANierbeck Need to check, but Is that package available in that ubuntu version of the base image?

**Comment by ANierbeck** [comment]
if not do something like the following: 

RUN add-apt-repository ppa:openjdk-r/ppa

prior the install ;)

**Comment by joerg84** [comment]
@ANierbeck but we don't do that ;-). Could you include this in your PR?

```root@d3dfe1209907:/# apt-get install openjdk-8-jdk
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package openjdk-8-jdk```

**Comment by ANierbeck** [comment]
done :)

**Comment by joerg84** [comment]
@ANierbeck can you quickly check my additional commits here?

**Comment by ANierbeck** [comment]
@joerg84 & @unterstein awesome guys ... 👍

**Pull request merged**
